apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-configmap
  namespace: project
data:
  postgres_host: "postgres-svc"
  postgres_port: "5432"
  postgres_db: "postgres"
  postgres_user: "postgres"
  postgres_password: "password"
  init.sql: |
    CREATE TABLE todos(todo TEXT);
