apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-addurl
  namespace: project
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-addurl
              image: prmckinney/todo-cronjob:2.9
              imagePullPolicy: IfNotPresent
              restartPolicy: OnFailure
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: todo-configmap
                      key: postgres_host
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: todo-configmap
                      key: postgres_port
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: todo-configmap
                      key: postgres_db
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: todo-configmap
                      key: postgres_user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: todo-configmap
                      key: postgres_password
