apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-todo
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo-app
          image: PROJECT/FRONTEND
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: BACKEND_URL
              value: "http://localhost:3000"
        - name: todo-backend
          image: PROJECT/IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: DIR
              value: "/usr/src/app/files"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: postgres_password
          volumeMounts:
            - name: shared-todo
              mountPath: /usr/src/app/files
