apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: project
spec:
  storageClassName: todo-scn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Mi
