apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/configmap.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
  - manifests/deployment.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
images:
  - name: PROJECT/FRONTEND
    newName: prmckinney/k3d_todo_app
    newTag: "4.2"
  - name: PROJECT/IMAGE
    newName: prmckinney/k3d_todo_backend
    newTag: "4.2"
