apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/configmap.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: PROJECT/BACKEND
  newName: prmckinney/k3d_todo_backend
  newTag: 2dcfa5be11ed562f23d5b3167a7e3f241672d35f
- name: PROJECT/FRONTEND
  newName: prmckinney/k3d_todo_app
  newTag: 2dcfa5be11ed562f23d5b3167a7e3f241672d35f
