apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/configmap.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
  - manifests/deployment.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
images:
  - name: EXERCISE/FRONTEND
    newName: prmckinney/k3d_log_output_server
    newTag: "4.1"
  - name: EXERCISE/BACKEND
    newName: prmckinney/k3d_log_output_write
    newTag: "1.10"
  - name: EXERCISE/PINGPONG
    newName: prmckinney/k3d_ping_pong
    newTag: "4.1"
